In [1]:
import numpy as np

In [2]:
print(np.pi)
print(np.cos(np.pi)) # cosine (pi) - pi=3.141..
print(np.sqrt(64))
print(np.log(np.exp(5.2))) #np.log is the logorithm of natural base which is 'e'
print(np.log10(10))

3.141592653589793
-1.0
8.0
5.2
1.0


In [3]:
#generate an array / vector
vector = np.array([1,2,4,5])
print(vector)

# generating matrix

matrix = np.array([[1,3,5],[3,6,7],[9,10,2]])
print(matrix)
print(matrix.T) # T - Transpose of a mtrix
print(np.linalg.det(matrix)) # Determinant of a matrix
print(np.linalg.inv(matrix)) # matrix inverse

matrrixWith0Det = np.array([[1,2], [1,2]])
print(matrrixWith0Det)
print(np.linalg.det(matrrixWith0Det))
# print(np.linalg.inv(matrrixWith0Det)) # Cannot find the inverse of a mtrix as the determinant is zero

[1 2 4 5]
[[ 1  3  5]
 [ 3  6  7]
 [ 9 10  2]]
[[ 1  3  9]
 [ 3  6 10]
 [ 5  7  2]]
-7.000000000000015
[[ 8.28571429 -6.28571429  1.28571429]
 [-8.14285714  6.14285714 -1.14285714]
 [ 3.42857143 -2.42857143  0.42857143]]
[[1 2]
 [1 2]]
0.0


In [15]:
vector1 = np.arange(0,10) #generates an array of 0 to 9 as the upper limit is exclusive
print(vector1)
vector2 = np.arange(2,10,3) # np.arrange(startvalue, endValue, stepSize) - generates an array from 2 to 10 execluding 10 with increment of 3, by default the step size is 1
print(vector2)

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]


In [23]:
vector3 = np.linspace(0,5, 10) # generates an array of values that are evenly spaced b/w 0 and 5. That is there will be 9 spaces b/w 0 and 5
print(vector3)
vector4 = np.linspace(1,5, 10) # generates an array of values that are evenly spaced b/w 1 and 5. That is there will be 9 spaces b/w 1 and 5
print(vector4)
print(np.reshape(vector3, (10,1)))
print(vector3) #reshape doesn't change the original vector it just returns a new array
vector5 = np.reshape(vector3, (5,2))
print(vector5)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[[0.        ]
 [0.55555556]
 [1.11111111]
 [1.66666667]
 [2.22222222]
 [2.77777778]
 [3.33333333]
 [3.88888889]
 [4.44444444]
 [5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [28]:
mat = np.zeros((5,3))
print(mat)

mat1 = np.ones((5,3))
print(mat1)

mat2 = np.identity(3)
print(mat2)
print(np.eye(2)) # eye is short form of identity matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [31]:
vec = np.arange(1,6)
vec1 = np.arange(2,7)
print(vec)
print(vec1)
print(vec + vec1)
print(vec * vec1)
print(np.sqrt(vec))
print(1/vec1) #  generates an array with values 1/(each element of vector vec1)

[1 2 3 4 5]
[2 3 4 5 6]
[ 3  5  7  9 11]
[ 2  6 12 20 30]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.5        0.33333333 0.25       0.2        0.16666667]


In [38]:
vector7 = np.array([[2],[3],[5]])
productVec = np.matmul(matrix, vector7)
print(productVec)

[[36]
 [59]
 [58]]


In [39]:
print(np.linalg.solve(matrix, productVec)) # gives the unknow vector that gives productVec by multiplying with matrix
# matrix * unknown_vector = productVec

[[2.]
 [3.]
 [5.]]


In [40]:
vec4 = np.array(['sri', 'naga', 'Kedari', 'sri', 'SRI', 'NaGa', 4])
print(vec4)
print(np.unique(vec4)) # Unique is case sensitive

['sri' 'naga' 'Kedari' 'sri' 'SRI' 'NaGa' '4']
['4' 'Kedari' 'NaGa' 'SRI' 'naga' 'sri']


In [53]:
# random array generators
random_mat = np.random.rand(5,5) # uniform random variable which means 0 < each element < 1
random_mat1 = np.random.randn(10,6) # standard normal varible which means a mean of 0 and a standard deviation of 1
random_mat2 = np.random.randint(2,10) # returns an integer b/w 2 to 10
print(random_mat)
print(random_mat1)
print(random_mat2)

[[0.37958521 0.08161862 0.98508426 0.75369388 0.39409301]
 [0.46018648 0.92554182 0.51278671 0.06944338 0.13990441]
 [0.75813018 0.04530817 0.22062851 0.80053599 0.97333334]
 [0.77350316 0.77241513 0.07680775 0.98357613 0.77156564]
 [0.33792335 0.23174351 0.26872157 0.89252487 0.3881423 ]]
[[ 1.28803097 -1.46914179 -0.72411495  0.87120873  1.47967171 -1.42326093]
 [-0.34925326 -1.29903716  0.2586732   1.48510261  0.54728547 -1.18581395]
 [-0.82641714 -0.92328964  0.49181498 -1.11040314 -0.10020005  0.71734968]
 [-2.10020617 -1.23556784  0.73173612  0.4291096   0.48395002 -0.63851581]
 [ 0.27386219 -0.15304408  1.1080321  -1.46989384  0.01892212  0.76251525]
 [-0.32406241 -0.26935994  0.75631252  1.11086435 -0.2719643   0.43939175]
 [-1.24612102  1.6708391  -0.76769624 -0.6772328  -0.25318291 -0.29137143]
 [-1.78308597  1.80952738  1.92610244  0.82930398  2.22838131  0.00942564]
 [ 0.39990275  0.91321983  0.07657049  0.22606402 -1.61129442  1.54163603]
 [ 1.13507878  2.18587273 -1.84495

In [55]:
print(np.mean(random_mat))
print(np.mean(random_mat1))
print(np.std(random_mat))
print(np.std(random_mat1))
print(np.min(random_mat))
print(np.max(random_mat))
print(np.min(random_mat1))
print(np.max(random_mat1))

0.5198718950060757
0.06299179300046907
0.3230005791039736
1.0845948459124815
0.04530816849099284
0.9850842593478119
-2.1002061653178177
2.2283813097760015
