In [1]:
import numpy as np

In [2]:
vec = np.random.randn(10)
print(vec)
print(vec[6])

[-2.39390551 -0.03039026  0.11072669 -0.1774862   1.55803038 -0.26818209
  0.57249639  0.51216023 -1.13394293  0.42486952]
0.5724963870906693


In [3]:
print(vec[4:9]) # array of elements from index 4 to 8 (9 is not inclusive)

[ 1.55803038 -0.26818209  0.57249639  0.51216023 -1.13394293]


In [4]:
print(np.arange(0,10,3))
print(vec[np.arange(0,10,3)]) # We can access elelments that are not in consecutive indexes

[0 3 6 9]
[-2.39390551 -0.1774862   0.57249639  0.42486952]


In [10]:
mat = np.random.rand(3,6)
print(mat) # prints the whole matix
print(mat[1]) # prints the secord row of the matrix
print(mat[1][1]) # print the second element of second row
print(mat[1, 3]) # prints fourth element of second row
print(mat[0:2, 1:3]) # prints rows 0,1 and columns 1,2

[[0.62818782 0.25018361 0.8761828  0.15090014 0.42907852 0.07999229]
 [0.25213574 0.90815934 0.53532156 0.98101941 0.19557038 0.57464531]
 [0.93341802 0.53832821 0.29737494 0.50006363 0.42561817 0.36155947]]
[0.25213574 0.90815934 0.53532156 0.98101941 0.19557038 0.57464531]
0.9081593411784821
0.9810194133329754
[[0.25018361 0.8761828 ]
 [0.90815934 0.53532156]]


In [25]:
# vec[3:8] = 'String Value' # Fails because of different data types
vec[3:8] = 10 # Updates the values of vector from the index 3 to 7 to value 10
print(vec)

[-2.39390551 -0.03039026  3.         10.         10.         10.
 10.         10.         -1.13394293  0.42486952]
[[ 0.62818782  0.25018361  0.8761828   0.15090014  0.42907852  0.07999229]
 [ 0.25213574  0.90815934  0.53532156  0.98101941  0.19557038  0.57464531]
 [15.          1.         15.         15.         15.         15.        ]]


In [27]:
vec[2:4] = [4,5] # replaces the values of vector with index 2 to and index 3 to 5 (the index space b/w lower and upper
# element should match the number of elements assigning. Ex: 4-2 = 2)
print(vec)

[-2.39390551 -0.03039026  4.          5.         10.         10.
 10.         10.         -1.13394293  0.42486952]


In [32]:
mat[2:3, 1:2] = 1 # Updates the values of matrix to 1 for the row index 2 and the columns with index 1
print(mat)
mat[1:2, 2:5] = 10 # Updates the values of matrix to 1 for the row index 2 and the columns with index 1
print(mat)
sub_mat = mat[1:3, 1:3]
sub_mat[:] = 6 # Setting all the values of sub matrix to 6
print(sub_mat)
print(mat) # Modifying the sub matrix effects the original matrix
# To avoid that, we need to use copy() operation
sub_mat = mat[0:2, 0:2].copy()
sub_mat[:]= 99
print(sub_mat)
print(mat)

[[ 0.62818782  0.25018361  0.8761828   0.15090014  0.42907852  0.07999229]
 [ 0.25213574  6.          6.         10.         10.          0.57464531]
 [15.          1.          6.         15.         15.         15.        ]]
[[ 0.62818782  0.25018361  0.8761828   0.15090014  0.42907852  0.07999229]
 [ 0.25213574  6.         10.         10.         10.          0.57464531]
 [15.          1.          6.         15.         15.         15.        ]]
[[6. 6.]
 [6. 6.]]
[[ 0.62818782  0.25018361  0.8761828   0.15090014  0.42907852  0.07999229]
 [ 0.25213574  6.          6.         10.         10.          0.57464531]
 [15.          6.          6.         15.         15.         15.        ]]
[[99. 99.]
 [99. 99.]]
[[ 0.62818782  0.25018361  0.8761828   0.15090014  0.42907852  0.07999229]
 [ 0.25213574  6.          6.         10.         10.          0.57464531]
 [15.          6.          6.         15.         15.         15.        ]]


In [44]:
mat1 = np.ones((3,6))
print(mat1)
mat1[0:2, 0:3] = [[20, 30, 50],
                 [40, 60, 80]]
print(mat1)
mat = np.random.rand(3,6)
print(mat)
mat[0:2, 0:3] = [[20, 30, 50],
                 [40, 60, 80]]
print(mat)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[20. 30. 50.  1.  1.  1.]
 [40. 60. 80.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
[[ 0.92535434  0.42758148 -0.67267745 -0.52604608  0.76019398  0.20277922]
 [ 0.88101877 -0.29370789 -0.7953827   0.66654268 -1.25732376  1.15390183]
 [-1.07248822  0.02981136  0.83568457  0.22916317  1.33031781 -0.98127406]]
[[ 2.00000000e+01  3.00000000e+01  5.00000000e+01 -5.26046082e-01
   7.60193982e-01  2.02779218e-01]
 [ 4.00000000e+01  6.00000000e+01  8.00000000e+01  6.66542677e-01
  -1.25732376e+00  1.15390183e+00]
 [-1.07248822e+00  2.98113625e-02  8.35684568e-01  2.29163171e-01
   1.33031781e+00 -9.81274056e-01]]
