In [2]:
import numpy as np

In [6]:
vec = np.random.randn(15)
print(vec)
print(vec>1) # prints true or false for each element based on the condition
print(vec[vec>0]) # prints array of values that match the condition

[ 0.64111816 -0.35846459 -0.12905204 -0.06573339  0.97195898  0.16105457
 -0.86666653 -0.14097122  1.08398019 -0.42074981  0.38659937  0.92970108
  0.54632815  1.63115093  2.1601995 ]
[False False False False False False False False  True False False False
 False  True  True]
[0.64111816 0.97195898 0.16105457 1.08398019 0.38659937 0.92970108
 0.54632815 1.63115093 2.1601995 ]


In [7]:
mat = np.random.randn(2,3)
print(mat)
print(mat>0)# prints true or false for each element based on the condition - result would be a matrix of original size
print(mat[mat>1]) # prints the array of elements that match the condition

[[-0.1951122  -1.03163347  0.01624062]
 [-0.07430631  0.38763418 -0.0676977 ]]
[[False False  True]
 [False  True False]]
[]


In [9]:
mat[mat>1] = 10 # Replaces all the elements that matches the condition with 10
print(mat)

[[-0.7606461  -0.75182342 -1.63333622]
 [-0.24775428 -0.17485426 10.        ]]


In [14]:
# Saving single array to a file
np.save('my-test-array', mat)

# Saving multiple arrays to a zip file. np.savez('zip_file_name', individual_file_name=array_you_want_store)
mat1 = np.random.randn(4,5)
np.savez('my-test-array-zip', first_matrix=mat, second_matrix=mat1) # filenames shouldn't contain '-'

In [5]:
loaded_mat = np.load('my-test-array.npy') # loads the file from the drive
loaded_mat_zip = np.load('my-test-array-zip.npz') # loads the zip file from the drive

print(loaded_mat) # prints the content (inthis case the matrix) of the file
print(loaded_mat_zip) # prints the memory location of the zip

mat_inside_zip = loaded_mat_zip['first_matrix']
print(mat_inside_zip)
mat_inside_zip1 = loaded_mat_zip['second_matrix']
print(mat_inside_zip1)

[[-0.7606461  -0.75182342 -1.63333622]
 [-0.24775428 -0.17485426 10.        ]]
[[-0.7606461  -0.75182342 -1.63333622]
 [-0.24775428 -0.17485426 10.        ]]
[[ 0.44791213  0.87321531 -1.14392837 -0.55052387 -0.72791002]
 [-0.26333137  2.34148832  0.85987812 -0.05630366  0.38827304]
 [-1.03232586  0.1405652  -0.61466876 -0.48956022 -1.82548566]
 [-0.38727964 -0.32446406 -0.28865347 -1.64198392 -1.27095903]]


In [10]:
np.savetxt('my-test-text-file.txt', mat, delimiter=';')

text_file_content = np.loadtxt('my-test-text-file.txt', delimiter=',')

print(text_file_content)

[[-0.1951122  -1.03163347  0.01624062]
 [-0.07430631  0.38763418 -0.0676977 ]]
